
development:
  secret_key_base: 07d517d8d25caa02725b79885e675f2c44c5383482c75a3a5ac0bcd3e3e1b8a9106f2105dde1477a295bc89aba89374d8baecc45e36894979402c06ec58a3ffe
  facebook_app_id: <%= ENV['facebook_app_id'] %>
  facebook_app_secret: <%= ENV['facebook_app_secret'] %>
test:
  secret_key_base: 3b7c12ad38142b2b36a628c95d66c8da41d7df3342bceae3545193526bd25f96f1e6ba388365ea880ac607390bb7ca9f657ed831592b238a4fcc3624b10df503
  facebook_app_id: <%= ENV['facebook_app_id'] %>
  facebook_app_secret: <%= ENV['facebook_app_secret'] %>
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
